import {SmallLinkModel} from "../interface/small-link-model";

export const skills: SmallLinkModel[] = [
    {
        id: "angular",
        img: "assets/skills/angular.svg",
        title: "Angular",
        desc: "",
        link: "https://angular.io/",
    },
    {
        id: "java",
        img: "assets/skills/java.svg",
        title: "Java",
        desc: "",
        link: "https://dev.java/",
    },
    {
        id: "spigot",
        img: "assets/skills/spigot.png",
        title: "Spigot",
        desc: "",
        link: "https://hub.spigotmc.org/javadocs/bukkit/",
    },
    {
        id: "html",
        img: "assets/skills/html5.svg",
        title: "HTML5",
        desc: "",
        link: "https://html.spec.whatwg.org/multipage/",
    },
    {
        id: "sass",
        img: "assets/skills/sass.svg",
        title: "Sass",
        desc: "",
        link: "https://sass-lang.com/",
    },
    {
        id: "js",
        img: "assets/skills/javascript.svg",
        title: "JavaScript",
        desc: "",
        link: "https://www.javascript.com/",
    },
    {
        id: "ts",
        img: "assets/skills/typescript.svg",
        title: "TypeScript",
        desc: "",
        link: "https://www.typescriptlang.org/",
    },
    {
        id: "git",
        img: "assets/skills/git.svg",
        title: "Git",
        desc: "",
        link: "https://git-scm.com/",
    },
    {
        id: "react",
        img: "assets/skills/reactjs.svg",
        title: "ReactJS",
        desc: "",
        link: "https://reactjs.org/",
    },
    {
        id: "insightmaker",
        img: "assets/skills/insightmaker.png",
        title: "Insight Maker",
        desc: "",
        link: "https://insightmaker.com/",
    },
    {
        id: "node",
        img: "assets/skills/nodejs.svg",
        title: "NodeJS",
        desc: "",
        link: "https://nodejs.org/",
    },
];
